fix: fix TypeError in ROI subsampling
The `subsample_rois` function will raise a TypeError if `fg_num_rois > 0 and bg_num_rois == 0`.
This is because the `bg_inds=[]` line. Later on `fg_inds` and `bg_inds` are concatenated with
`sampled_inds = torch.cat((fg_inds, bg_inds), dim=0)`. This will yield TypeError

Steps to reproduce:
```
>>> import torch
>>> a = torch.tensor([1,2,3])
>>> b = []
>>> torch.cat([a,b], axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: expected Tensor as element 1 in argument 0, but got list
```

An easy fix is to let `bg_inds` be an empty tensor of same dtype and device as `fg_inds`